# Generated by Django 4.2.6 on 2023-11-08 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название категории')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-категории')),
            ],
            options={
                'verbose_name': 'Категория новостей',
                'verbose_name_plural': 'Категории новостей',
            },
        ),
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('img', models.ImageField(upload_to='news/%Y/%m/%d/', verbose_name='Главное фото')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL-новости')),
                ('content', models.TextField(verbose_name='Контент')),
                ('date_publish', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.categorynews', verbose_name='Тема новости')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='NewsCommentsModefl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='Комментатор')),
                ('user_email', models.EmailField(max_length=100, verbose_name='e-mail комментатора')),
                ('comment', models.TextField(max_length=5000, verbose_name='Комментарий')),
                ('date_publish', models.DateField(auto_now_add=True, verbose_name='Дата комментария')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.newsmodel', verbose_name='Новость')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.newscommentsmodefl', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
