# Generated by Django 4.2.6 on 2023-10-25 14:17

import createx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AskFromUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100, verbose_name='Имя пользователя')),
                ('phoneNumberUser', models.CharField(error_messages={'invalid': 'Введите в формате 00x00 или 000x000'}, max_length=50, validators=[createx.models.ValidateNumberPhone], verbose_name='Номер телефона')),
                ('askContent', models.TextField(max_length=5000, verbose_name='Вопрос от пользователя')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата вопроса')),
            ],
            options={
                'verbose_name': 'Вопрос от пользователя',
                'verbose_name_plural': 'Вопросы от пользователей',
            },
        ),
        migrations.CreateModel(
            name='DiscussForUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100, verbose_name='Имя пользователя')),
                ('phoneNumberUser', models.CharField(error_messages={'invalid': 'Введите в формате 00x00 или 000x000'}, max_length=50,
                                                     validators=[createx.models.ValidateNumberPhone], verbose_name='Номер телефона')),
                ('emailUser', models.EmailField(max_length=100, unique=True, verbose_name='E-mail пользователя')),
                ('discussContent', models.TextField(max_length=5000, verbose_name='Обсуждение от пользователя')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата подписки')),
                ('userAgree', models.BooleanField(default=False, verbose_name='Согласие на ответ')),
            ],
            options={
                'verbose_name': 'Обсуждение от подписчика',
                'verbose_name_plural': 'Обсуждение от подписчиков',
            },
        ),
        migrations.CreateModel(
            name='HeaderContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('content', models.TextField(max_length=1000, verbose_name='Содержание')),
                ('img', models.ImageField(upload_to='header/%Y/%m/%d/', verbose_name='Фотография')),
            ],
        ),
        migrations.CreateModel(
            name='MainSliderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('content', models.CharField(max_length=500, verbose_name='Содержание')),
                ('imageSlider', models.ImageField(upload_to='mainSlider/%Y/%m/%d/', verbose_name='Фотография')),
                ('isPublished', models.BooleanField(default=True, verbose_name='Опубликовать')),
            ],
            options={
                'verbose_name': 'Главный слайдер',
                'verbose_name_plural': 'Главный слайдер',
            },
        ),
        migrations.CreateModel(
            name='OurClientsReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iconClient', models.ImageField(upload_to='clientReview/photoClient/%Y/%m/%d/', verbose_name='Логотип')),
                ('mainImg', models.ImageField(upload_to='clientReview/mainImg/%Y/%m/%d/', verbose_name='Фотография')),
                ('contentReview', models.TextField(max_length=300, verbose_name='Отзыв')),
                ('nameClient', models.CharField(max_length=50, verbose_name='Имя клиента')),
                ('nameCompany', models.CharField(max_length=100, verbose_name='Название компании')),
                ('adressCompeny', models.CharField(max_length=100, verbose_name='Адрес компании')),
            ],
            options={
                'verbose_name': 'Отзыв клиента',
                'verbose_name_plural': 'Отзывы клиентов',
            },
        ),
        migrations.CreateModel(
            name='OurCoreValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleCore', models.CharField(max_length=50, verbose_name='Название')),
                ('contentCore', models.TextField(max_length=500, verbose_name='Содержание')),
                ('coreIcon', models.ImageField(upload_to='coreValues/%Y/%m/%d/', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Наша ценность',
                'verbose_name_plural': 'Наши ценности',
            },
        ),
        migrations.CreateModel(
            name='OurPartners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namePartners', models.CharField(max_length=30, verbose_name='Имя')),
                ('slug', models.SlugField(max_length=35, verbose_name='url-partners')),
                ('logo', models.ImageField(upload_to='ourPartners/%Y/%m/%d/', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Наш партнер',
                'verbose_name_plural': 'Наши партнеры',
            },
        ),
        migrations.CreateModel(
            name='UserSubscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userEmail', models.EmailField(max_length=100, verbose_name='E-mail подписчика')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата подписки')),
            ],
            options={
                'verbose_name': 'Наш подписчик',
                'verbose_name_plural': 'Наши подписчики',
            },
        ),
    ]
