# Generated by Django 4.2.6 on 2023-10-27 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createx', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headercontent',
            options={'verbose_name': 'Заголовок страницы', 'verbose_name_plural': 'Заголовоки страниц'},
        ),
    ]
